# Generated by Django 4.0.3 on 2022-04-02 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('userpass', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('item_type', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('parameters', models.CharField(max_length=20)),
                ('package', models.CharField(max_length=20)),
                ('picture', models.CharField(max_length=20)),
                ('item_description', models.CharField(max_length=20)),
                ('cost_centre', models.CharField(max_length=20)),
                ('reg_number', models.CharField(max_length=20)),
                ('purchase_data', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('purchase_place', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(max_length=20)),
                ('categoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='varasto.category')),
            ],
        ),
        migrations.CreateModel(
            name='Storage_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Storage_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack', models.CharField(max_length=20)),
                ('shelf', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=30)),
                ('itemID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='varasto.goods')),
                ('storage_nameID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='varasto.storage_name')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=100)),
                ('from_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_storage', to='varasto.storage_place')),
                ('itemID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='varasto.goods')),
                ('to_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_storage', to='varasto.storage_place')),
            ],
        ),
        migrations.CreateModel(
            name='Rental_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=255)),
                ('itemID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='varasto.goods')),
                ('storageID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='varasto.storage_place')),
            ],
        ),
    ]
