# Generated by Django 4.0.3 on 2022-04-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('student_ext', 'Student extended'), ('storage_employee', 'Storage employee'), ('management', 'Management')], max_length=255),
        ),
    ]
