# Generated by Django 4.0.3 on 2022-04-13 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_event',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/students/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('student_ext', 'Student extended'), ('storage_employee', 'Storage employee'), ('management', 'Management')], default='student', max_length=255),
        ),
        migrations.AlterField(
            model_name='goods',
            name='cat_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='varasto.category'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/goods/'),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='varasto.goods'),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='varasto.storage_place'),
        ),
        migrations.AlterField(
            model_name='staff_event',
            name='from_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_storage', to='varasto.storage_place'),
        ),
        migrations.AlterField(
            model_name='staff_event',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='varasto.goods'),
        ),
        migrations.AlterField(
            model_name='staff_event',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff_event',
            name='to_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_storage', to='varasto.storage_place'),
        ),
        migrations.AlterField(
            model_name='storage_place',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='varasto.goods'),
        ),
        migrations.AlterField(
            model_name='storage_place',
            name='storage_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='varasto.storage_name'),
        ),
    ]
