# Generated by Django 4.0.3 on 2022-04-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0003_staff_event_amount_alter_customuser_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('student_ext', 'Student extended'), ('storage_employee', 'Storage employee'), ('management', 'Management'), ('teacher', 'Teacher')], default='student', max_length=255),
        ),
    ]
