# Generated by Django 4.0.3 on 2022-04-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
