# Generated by Django 4.0.3 on 2022-04-13 08:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0005_customuser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental_event',
            name='estimated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental_event',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 4, 13, 11, 35, 42, 218336)),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='varasto.goods'),
        ),
    ]
