# Generated by Django 4.0.3 on 2022-04-17 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0006_rental_event_estimated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 4, 17, 17, 6, 29, 320523)),
        ),
    ]
