# Generated by Django 4.0.3 on 2022-04-17 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0007_alter_rental_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('student_ext', 'Student extended'), ('storage_employee', 'Storage employee'), ('management', 'Management'), ('teacher', 'Teacher'), ('super', 'Super')], default='student', max_length=255),
        ),
        migrations.AlterField(
            model_name='goods',
            name='brand',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='cost_centre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goods',
            name='invoice_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='goods',
            name='item_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='item_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='goods',
            name='item_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='model',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='package',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='goods',
            name='parameters',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='purchase_place',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='goods',
            name='reg_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 4, 17, 17, 24, 11, 229946)),
        ),
    ]
