# Generated by Django 4.0.3 on 2022-05-03 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0008_alter_customuser_role_alter_goods_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='cost_centre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='item_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='package',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='purchase_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='purchase_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 5, 3, 12, 15, 50, 918208)),
        ),
    ]
