# Generated by Django 4.0.3 on 2022-05-03 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0009_alter_goods_cost_centre_alter_goods_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 5, 3, 18, 55, 52, 481473)),
        ),
    ]
