# Generated by Django 4.0.3 on 2022-05-09 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0010_alter_rental_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_event',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 5, 9, 13, 1, 34, 865972)),
        ),
    ]
