# Generated by Django 4.0.3 on 2022-05-09 14:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0011_staff_event_event_date_alter_rental_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 5, 9, 17, 17, 20, 345805)),
        ),
        migrations.AlterField(
            model_name='staff_event',
            name='from_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_storage', to='varasto.storage_name'),
        ),
        migrations.AlterField(
            model_name='staff_event',
            name='to_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_storage', to='varasto.storage_name'),
        ),
    ]
