# Generated by Django 4.0.3 on 2022-05-09 14:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0012_alter_rental_event_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage_place',
            name='storage_name',
        ),
        migrations.AddField(
            model_name='storage_name',
            name='storage_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='varasto.storage_place'),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 5, 9, 17, 47, 13, 475725)),
        ),
    ]
