# Generated by Django 4.0.3 on 2022-05-09 14:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0013_remove_storage_place_storage_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage_place',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='storage_place',
            name='item',
        ),
        migrations.AddField(
            model_name='goods',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='varasto.storage_name'),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 5, 9, 17, 52, 20, 973886)),
        ),
    ]
