# Generated by Django 4.0.3 on 2022-05-10 07:50

from asyncio.windows_events import NULL
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0014_remove_storage_place_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='ean',
            field=models.IntegerField(default=NULL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 5, 10, 10, 50, 11, 819454)),
        ),
    ]
