# Generated by Django 4.0.3 on 2022-05-10 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0019_alter_goods_amount_alter_goods_ean_alter_goods_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 5, 10, 12, 27, 52, 678866)),
        ),
    ]
