# Generated by Django 4.0.3 on 2022-05-10 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0020_alter_rental_event_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='package',
            new_name='pack',
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 5, 10, 13, 9, 16, 388703)),
        ),
    ]
