# Generated by Django 4.0.3 on 2022-05-10 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0021_rename_package_goods_pack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='ean',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 5, 10, 13, 16, 6, 48671)),
        ),
    ]
