# Generated by Django 4.0.3 on 2022-05-10 11:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0023_remove_staff_event_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 5, 10, 14, 5, 8, 64731)),
        ),
        migrations.AlterField(
            model_name='staff_event',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='varasto.goods'),
        ),
        migrations.AlterField(
            model_name='staff_event',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
