# Generated by Django 4.0.3 on 2022-05-11 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0024_alter_rental_event_start_date_alter_staff_event_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='units',
            field=models.CharField(blank=True, choices=[('unit', 'kpl'), ('litre', 'l'), ('kilogram', 'kg')], default='unit', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 5, 11, 8, 35, 1, 701527)),
        ),
    ]
