# Generated by Django 4.0.3 on 2022-05-18 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0027_goods_item_status_alter_rental_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Oppilas'), ('student_extended', 'Oppilas laajennetut oikeudet'), ('storage_employee', 'Varastotyöntekijä'), ('management', 'Hallinto'), ('teacher', 'Opettaja'), ('super', 'Super user')], default='student', max_length=255),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 5, 18, 11, 6, 45, 813073)),
        ),
    ]
