# Generated by Django 4.0.3 on 2022-06-21 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0028_alter_customuser_role_alter_rental_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage_name',
            name='storage_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 6, 21, 11, 49, 43, 614868)),
        ),
    ]
