# Generated by Django 4.0.3 on 2022-06-21 09:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0030_customuser_storge_alter_rental_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='storge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='varasto.storage_name'),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 6, 21, 12, 10, 32, 271940)),
        ),
    ]
