# Generated by Django 4.0.3 on 2022-09-19 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0033_goods_storage_place_alter_rental_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 9, 19, 11, 52, 41, 30585)),
        ),
    ]
