# Generated by Django 4.0.3 on 2022-09-19 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0034_alter_goods_item_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varasto_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(blank=True, max_length=50, null=True)),
                ('set_value', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 9, 19, 20, 26, 38, 47265)),
        ),
    ]
