# Generated by Django 4.0.3 on 2022-09-25 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0036_rename_varasto_settings_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental_event',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 9, 25, 11, 2, 27, 939478)),
        ),
    ]
