# Generated by Django 4.0.3 on 2022-09-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0037_rental_event_amount_alter_rental_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
