# Generated by Django 4.0.3 on 2022-09-29 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0038_alter_rental_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_event',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='varasto.storage_name'),
        ),
    ]
