# Generated by Django 4.0.3 on 2022-10-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0039_alter_rental_event_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(blank=True, default='images/goods/67.jpg', null=True, upload_to='images/goods/'),
        ),
    ]
