# Generated by Django 4.0.3 on 2022-10-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0040_alter_goods_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='brand',
            field=models.CharField(default='no brand', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/goods/'),
        ),
    ]
