# Generated by Django 4.0.3 on 2022-11-03 08:36

from django.db import migrations, models
import varasto.models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0041_alter_goods_brand_alter_goods_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='amount',
            field=varasto.models.IntegerRangeField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='ean',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='units',
            field=models.CharField(blank=True, choices=[('unit', 'kpl'), ('litre', 'l'), ('kilogram', 'kg'), ('meter', 'm')], max_length=50, null=True),
        ),
    ]
