# Generated by Django 4.0.3 on 2022-11-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0042_alter_goods_amount_alter_goods_ean_alter_goods_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='pack',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
    ]
