# Generated by Django 4.0.3 on 2022-11-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0044_rename_pack_goods_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, choices=[('unit', 'kpl'), ('litre', 'l'), ('kilogram', 'kg'), ('meter', 'm')], max_length=50, null=True)),
            ],
        ),
    ]
