# Generated by Django 4.0.3 on 2022-11-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0047_alter_units_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='varasto.units'),
        ),
    ]
