# Generated by Django 4.0.3 on 2022-11-24 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0049_alter_goods_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='units',
            old_name='unit',
            new_name='unit_name',
        ),
        migrations.AlterField(
            model_name='goods',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit', to='varasto.units'),
        ),
    ]
