# Generated by Django 4.0.3 on 2022-11-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0050_rename_unit_units_unit_name_alter_goods_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unitss', to='varasto.units'),
        ),
    ]
