# Generated by Django 4.0.3 on 2022-11-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0054_goods_amount_x_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='amount_x_units',
            new_name='amount_x_contents',
        ),
    ]
