# Generated by Django 4.0.3 on 2022-11-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0056_alter_goods_cost_centre_alter_goods_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='brand',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
