# Generated by Django 4.0.3 on 2022-11-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0057_alter_goods_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='cost_centre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
