# Generated by Django 4.0.3 on 2022-11-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0059_rental_event_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_event',
            name='returned',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11, null=True),
        ),
    ]
