# Generated by Django 4.0.3 on 2022-12-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0060_alter_rental_event_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='units',
        ),
    ]
