# Generated by Django 4.0.3 on 2023-01-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0064_alter_staff_audit_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_audit',
            name='item',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staff_audit',
            name='person',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='staff_audit',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='staff_audit',
            name='staff',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
