# Generated by Django 4.0.3 on 2023-01-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0065_alter_staff_audit_item_alter_staff_audit_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='set_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='set_value',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
