# Generated by Django 4.0.3 on 2023-01-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0066_alter_settings_set_name_alter_settings_set_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/varastousers/'),
        ),
    ]
