# Generated by Django 4.0.3 on 2023-01-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0067_alter_customuser_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage_name',
            name='storage_place',
        ),
    ]
