# Generated by Django 4.0.3 on 2023-01-30 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0068_remove_storage_name_storage_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings_CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_value', models.CharField(blank=True, max_length=300, null=True)),
                ('setting_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varasto.settings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
