# Generated by Django 4.0.3 on 2023-02-09 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0069_settings_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='label',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='settings_customuser',
            name='setting_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_name', to='varasto.settings'),
        ),
        migrations.AlterField(
            model_name='settings_customuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
