# Generated by Django 4.0.3 on 2023-02-09 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0070_settings_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings_customuser',
            name='storage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='varasto.storage_name'),
        ),
    ]
