# Generated by Django 4.0.3 on 2023-02-09 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0071_settings_customuser_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_customuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
