# Generated by Django 4.0.3 on 2023-03-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0073_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_storage_staff',
            field=models.BooleanField(default=False),
        ),
    ]
