# Generated by Django 4.0.3 on 2023-03-10 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0075_remove_goods_item_status_remove_goods_reg_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_event',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='varasto.goods'),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='varasto.storage_name'),
        ),
        migrations.AlterField(
            model_name='rental_event',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='varasto.units'),
        ),
    ]
