# Generated by Django 4.0.3 on 2023-03-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0076_alter_rental_event_item_alter_rental_event_renter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage_name',
            name='storage_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
