# Generated by Django 4.0.3 on 2023-03-21 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0077_alter_storage_name_storage_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='varasto.storage_name'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit', to='varasto.units'),
        ),
    ]
