# Generated by Django 4.0.3 on 2023-03-21 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0078_alter_goods_storage_alter_goods_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='varasto.storage_name'),
        ),
    ]
